### ISSUE TITLE
where's the code?

### ISSUE THREAD

**Issue by i3roly** [keenetic/keenetic-sdk#1]
for example,

i see directories like package/kernel/mt7615

https://github.com/keenetic/keenetic-sdk/tree/main/package/kernel/mt7615

 but there is no code. it seems like all the good stuff is missing>?

**Comment by eyudin** [comment]
Hey!
The SDK is for rebuilding open source firmware packages.
All proprietary components are unpacked from the firmware.

**Comment by i3roly** [comment]
i assume you guys build the mt_wifi driver as a module then?

i may be intrigued enough to take it out of the firmware.

**Comment by inste** [comment]
@i3roly why don't you simple write to MTK? mt_wifi and ranat is a proprietary software of MTK, and we have no rights to distribute it.

If you want to play with sdk it is a very recommended to have a Keenetic to download firmwares from.

**Comment by i3roly** [comment]
I would, but I don't know who to contact.

Could you better assist in directing me to the people? I'm not opposed to your suggestion but I haven't been able to find the correct point of contact.

From: Ilya
Sent: Friday, 23 April 2021 10:11 AM
To: keenetic/keenetic-sdk
Reply To: keenetic/keenetic-sdk
Cc: gagan sidhu; Mention
Subject: Re: [keenetic/keenetic-sdk] where's the code? (#1)


@i3roly<https://github.com/i3roly> why don't you simple write to MTK? mt_wifi and ranat is a proprietary software of MTK, and we have no rights to distribute it.

If you want to play with sdk it is a very recommended to have a Keenetic to download firmwares from.

**Comment by inste** [comment]
We don't have either. I wonder if our B2B contact in MTK will have any desire to talk with ordinary customers.

**Comment by i3roly** [comment]
Well I guess I am a pleb since I am not making firmwares for that many devices.

But I would argue, probably aside from your firmware, my firmware is the best choice since dd-wrt inexplicably adopted the mt76 driver, which is a poor performer.

I have used the dd-wrt sources to make a dd-wrt that uses the proprietary driver that performs quite well and provides a rich feature set.

I feel people with the dlink models I do create the firmware for, would agree it's the best firmware.

Could you ask this contact? I would sign the ndas, of course. That's not a problem.

From: Ilya
Sent: Friday, 23 April 2021 11:26 AM
To: keenetic/keenetic-sdk
Reply To: keenetic/keenetic-sdk
Cc: gagan sidhu; Mention
Subject: Re: [keenetic/keenetic-sdk] where's the code? (#1)


We don't have either. I wonder if our B2B contact in MTK will have any desire to talk with ordinary customers.

**Comment by jwdoyler** [comment]
Dear Gagan Sidhu,
Thank you for contacting us. We greatly value hearing the views and opinions of the wider expert community. 
 
We have considered your request and produced the following official and final Keenetic response to your request to share the source code of the MTK driver.
 
Our official position is as follows:
 
Due to contractual obligations and restrictions that govern the commercial relationship between MTK and Keenetic Limited, we, Keenetic, are not legally able to share the source code of the MTK driver as requested. Furthermore, under the same commercial arrangements, we are not able to supply MTK contacts to unrelated third parties. 

This is our position. We see no obvious reason why this position would change now or in the foreseeable future, and politely withdraw from further discussion of this particular subject.
 
With regard to GPL related obligations, we are firmly of the opinion that:
•	Because the MTK driver is not GPL software, our ability to produce source code has no relevance to our GPL status; and 
•	Having published the SDK, Keenetic is fully compliant with GPL Licence needs.
 
Thank you for your interest in our operations, we wish you success in your future endeavours
 
J Doyle
